### ISSUE TITLE
"published at" field is inaccurate

### ISSUE THREAD

**Issue by aherrmann** [bazel-contrib/bcr-ui#140]
The BCR UI shows a version history panel for each module in the registry. Each entry includes a "published X days ago" (or other unit of time) field. That field shows the same time for each version, even if they were not in fact uploaded at the same time, and later uploads did not touch the previous versions. E.g. for rules_haskell it shows the following at the time of writing:
![image](https://github.com/bazelbuild/bazel-central-registry/assets/732652/5fb195a4-d9cb-4658-aef3-634c2e031ee8)
I.e. "published 14 days ago" and all link to the same commit https://github.com/bazelbuild/bazel-central-registry/commit/3e3619726711fb2db7c9a484e8689dd115cd38d7. That commit only touched version 0.19.

I would expect the "published at" field of the other versions to display the time when that version was actually added to the BCR.

**Comment by hobofan** [comment]
Thanks for the report!

I'll take a deeper look at it the next days, but my first guess is that the most likely cause is [this PR](https://github.com/bazel-contrib/bcr-ui/pull/118), which has introduced memoization, but potentially with a wrong cache key.
