### ISSUE TITLE
Fix sort order of module versions  

### ISSUE THREAD

**Issue by hobofan** [bazel-contrib/bcr-ui#16]
In the version history section for a module, it's currently sorted in ascending lexical order.

To improve it, it would probably be better to sort in a way that lists the most recently published versions first (which should also work with modules that have a non-semver version number). 

Example:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/601283/184666670-5727cbbf-6fe5-40b5-a3eb-0c0c2c497079.png">

**Comment by alexeagle** [comment]
I'd add that we should elide a long history like this, it's not useful to show every version. Simple thing would be to paginate I think.
