### ISSUE TITLE
Use a better link to release notes

### ISSUE THREAD

**Issue by hobofan** [bazel-contrib/bcr-ui#58]
Background / prior discussions: https://github.com/bazel-contrib/bcr-ui/pull/49, https://github.com/bazel-contrib/bcr-ui/pull/37#issuecomment-1378131591, https://github.com/bazelbuild/bazel-central-registry/issues/357

TLDR: We are using a link based on the assumption that the release tag has the format `v{VERSION}`, which is true for a big percentage of packages, but not 100% reliable

Ideas and suggestions on how to achieve this are welcome!

**Comment by hobofan** [comment]
As discussed at BazelCon, it's probably viable to call the Github API from the frontend to at least determine the module version format

**Comment by alexeagle** [comment]
Yeah the `tag` column on https://bazel-contrib.github.io/bazel-catalog/ shows the data we want I think, and it requests https://img.shields.io/github/v/tag/seh/rules_kustomize. But I think shields.io has a backend server that talks to github API, not done from the web client.

I'm imagining a really simple solution here: first do https://github.com/bazel-contrib/bcr-ui/issues/94 to render the latest tag badge, then we can edit the DOM to copy from the node created by the svg response and use that to create the release notes link.
